# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryBanIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP \u0430\u0434\u0440\u0435\u0441')),
                ('attempts', models.IntegerField(default=0, verbose_name='\u041d\u0435\u0443\u0434\u0430\u0447\u043d\u044b\u0445 \u043f\u043e\u043f\u044b\u0442\u043e\u043a')),
                ('time_unblock', models.DateTimeField(blank=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0440\u0430\u0437\u0431\u043b\u043e\u043a\u0438\u0440\u043e\u0432\u043a\u0438')),
                ('status', models.BooleanField(default=False, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0431\u043b\u043e\u043a\u0438\u0440\u043e\u0432\u043a\u0438')),
            ],
            options={
                'db_table': 'TemporaryBanIp',
            },
        ),
    ]
