# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='temporarybanip',
            table='temporarybanIp',
        ),
    ]
