# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170620_1339'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='temporarybanip',
            table='temporarybanip',
        ),
    ]
