# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_date', models.DateTimeField(verbose_name=b'Date published')),
                ('article_content', models.TextField()),
                ('article_status', models.IntegerField()),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200)),
                ('section_url', models.CharField(max_length=50)),
                ('section_description', models.TextField()),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Section'),
        ),
    ]
