# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170619_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlestatistic',
            name='date2',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=b'Date'),
        ),
    ]
