# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_articlestatistic_date2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestatistic',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
    ]
