# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170621_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestatistic',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
    ]
